# Generated by Django 3.2.8 on 2022-03-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100, verbose_name='Hospital Name')),
                ('problem_dignosed', models.CharField(max_length=200, verbose_name='Problem Dignosed')),
                ('surgery_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Surgery Name')),
                ('cost', models.IntegerField(verbose_name='Cost of Surgery/Procedure')),
                ('receipt_file', models.FileField(help_text='max. 42 megabytes', upload_to='', verbose_name='Receipt File')),
            ],
            options={
                'verbose_name': 'Patient Data',
                'verbose_name_plural': 'Patient Data',
            },
        ),
    ]
