# Generated by Django 4.0.1 on 2022-03-17 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100, verbose_name='Hospital Name')),
                ('problem_dignosed', models.CharField(max_length=200, verbose_name='Problem Dignosed')),
                ('surgery_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Surgery Name')),
                ('cost', models.IntegerField(verbose_name='Cost of Surgery/Procedure')),
                ('receipt_file', models.FileField(help_text='max. 42 megabytes', upload_to='receipts/', verbose_name='Receipt File')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Patient ID')),
            ],
            options={
                'verbose_name': 'Patient Data',
                'verbose_name_plural': 'Patient Data',
            },
        ),
    ]
