# Generated by Django 4.0.1 on 2022-03-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='receipt_file',
            field=models.FileField(help_text='max. 42 megabytes', upload_to='', verbose_name='Receipt File'),
        ),
    ]
